---
title: "LarvaeMorphology"
output: html_document
---

setwd("~/Desktop/Repos/LarvaeTransGen2018")

# Load libraries
```{r include=FALSE}
library(tidyverse)
```

# Load data
```{r}
larvmorph <- read.csv("../data/Larvae_morphology.csv")

larvmorph <- larvmorph %>%
  mutate(ParTrt = ifelse(startsWith(as.character(CrossID), "E"), "Exposed", "Control"))
```

# Plots of length data by individual crosses
```{r}
exlar <- larvmorph %>%
  filter(JarTrt == "Exposed")
colar <- larvmorph %>%
  filter(JarTrt == "Control")

ggplot(data = exlar, aes(x = CrossID, y = MaxFeretDiamum, fill = ParTrt)) +
  geom_boxplot() +
  labs(x = "Parental Cross", y = "Shell Length (um)", title = "OA Larvae") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  scale_fill_manual(name = "Parental Treatment", labels = c("Control", "OA"), 
                     values = c("#00BFC4", "#F8766D")) + 
  scale_y_continuous(breaks = seq(floor(min(larvmorph$MaxFeretDiamum)), 
                                ceiling(max(larvmorph$MaxFeretDiamum)), 5)) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        panel.background = element_blank(), axis.line = element_line(colour = "black"))

ggplot(data = colar, aes(x = CrossID, y = MaxFeretDiamum, fill = ParTrt)) +
  geom_boxplot() +
  labs(x = "Parental Cross", y = "Shell Length (um)", title = "Control Larvae") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  scale_fill_manual(name = "Parental Treatment", labels = c("Control", "OA"), 
                      values = c("#00BFC4", "#F8766D")) + 
  scale_y_continuous(breaks = seq(floor(min(larvmorph$MaxFeretDiamum)), 
                                ceiling(max(larvmorph$MaxFeretDiamum)), 5)) +  
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
```

# Plot of overall length data
```{r}
ggplot(data = larvmorph, aes(x = ParTrt, y = MaxFeretDiamum, fill = JarTrt)) +
  geom_boxplot() + 
  labs(x = "Parental Treatment", y = "Shell Length (um)") +
  scale_x_discrete(breaks = c("Control", "Exposed"), labels = c("Control", "OA")) +
  scale_fill_manual(name = "Larval Treatment", labels = c("Control", "OA"), 
                    values = c("#00BFC4", "#F8766D")) + 
  scale_y_continuous(breaks = seq(55,80,5)) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
```

# Plots of difference between parental treatments
```{r}
crossdiff <- data.frame(tapply(larvmorph$MaxFeretDiamum, list(larvmorph$CrossID, larvmorph$JarTrt), median)) %>%
  rownames_to_column("CrossID") %>%
  mutate(ParTrt = ifelse(startsWith(CrossID, "E"), "Exposed", "Control")) %>%
  mutate(Diff = Exposed - Control)

ggplot(data = crossdiff, aes(x = ParTrt, y = Diff, fill = ParTrt)) + 
  geom_boxplot() + 
  labs(x = "Parental Treatment", y = "Change in median shell length (um) per family\nfrom control to OA conditions") + 
  scale_x_discrete(breaks = c("Control", "Exposed"), labels = c("Control", "OA")) + 
  scale_fill_manual(values = c("#00BFC4", "#F8766D")) + 
  theme(legend.position = "none", panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
```